version: "3"
networks:
  proxynet:
    driver: bridge

services:
  backend:
    container_name: backend
    build: ./backend
    restart: always
    networks:
      - proxynet
    ports:
      - "8989:8989"
    # command: gunicorn -w 2 -b :5000 wsgi:server
    volumes:
      - "./backend/logs:/backend/logs"

  media_server:
    container_name: media_server
    restart: always
    build: ./media_server
    ports:
      - "1935:1935"
      - "8080:8080"
    networks:
      - proxynet
    volumes:
      - "./media_server/logs:/var/log/nginx"
      - "./media_server/logs/stream_manager.log:/logs/stream_manager.log"

  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    restart: always
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    networks:
      - proxynet

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: redis-commander
    restart: always
    environment:
    - REDIS_HOSTS=redis
    ports:
    - "8081:8081"
    networks:
      - proxynet